# Generated by Django 4.2.1 on 2023-05-03 18:45

from django.db import migrations, models
import django.db.models.deletion
import django_cpf_cnpj.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100)),
                ('cpf', django_cpf_cnpj.fields.CPFField(max_length=14)),
                ('cnpj', django_cpf_cnpj.fields.CNPJField(max_length=18)),
                ('data_cadastro', models.DateTimeField(verbose_name='Data Cadastro')),
            ],
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boleto_mes', models.CharField(max_length=10)),
                ('data_boleto', models.DateTimeField(verbose_name='Data Boleto')),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cristal.cliente')),
            ],
        ),
    ]
