# Generated by Django 4.2.1 on 2023-05-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cristal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='boleto_mes',
        ),
        migrations.AddField(
            model_name='tarefa',
            name='mes',
            field=models.CharField(choices=[('janeiro', 'JANEIRO'), ('fevereiro', 'FEVEREIRO'), ('marco', 'MARÇO'), ('abril', 'ABRIL'), ('maio', 'MAIO'), ('junho', 'JUNHO'), ('julho', 'JULHO'), ('agosto', 'AGOSTO'), ('setembro', 'SETEMBRO'), ('outubro', 'OUTUBRO'), ('novembro', 'NOVEMBRO'), ('dezembro', 'DEZEMBRO')], default='null', max_length=10),
        ),
    ]
