# Generated by Django 4.2.1 on 2023-05-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cristal', '0002_remove_tarefa_boleto_mes_tarefa_mes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='boleto',
            field=models.FileField(default='null', upload_to='documents/'),
        ),
    ]
