# Generated by Django 4.2.1 on 2023-05-03 19:07

from django.db import migrations, models
import django_cpf_cnpj.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cristal', '0003_tarefa_boleto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cnpj',
            field=django_cpf_cnpj.fields.CNPJField(default='null', max_length=18),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=django_cpf_cnpj.fields.CPFField(default='null', max_length=14),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='boleto',
            field=models.FileField(default='null', upload_to='cristal/static/cristal/'),
        ),
    ]
