# Generated by Django 4.2.1 on 2023-05-03 19:16

from django.db import migrations, models
import django_cpf_cnpj.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cristal', '0004_alter_cliente_cnpj_alter_cliente_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cnpj',
            field=django_cpf_cnpj.fields.CNPJField(blank=True, max_length=18),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=django_cpf_cnpj.fields.CPFField(blank=True, max_length=14),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='data_boleto',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data Boleto'),
        ),
    ]
