# Generated by Django 4.2.1 on 2023-05-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cristal', '0005_alter_cliente_cnpj_alter_cliente_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='mes',
            field=models.CharField(choices=[('JANEIRO', 'JANEIRO'), ('FEVEREIRO', 'FEVEREIRO'), ('MARÇO', 'MARÇO'), ('ABRIL', 'ABRIL'), ('MAIO', 'MAIO'), ('JUNHO', 'JUNHO'), ('JULHO', 'JULHO'), ('AGOSTO', 'AGOSTO'), ('SETEMBRO', 'SETEMBRO'), ('OUTUBRO', 'OUTUBRO'), ('NOVEMBRO', 'NOVEMBRO'), ('DEZEMBRO', 'DEZEMBRO')], default='null', max_length=10),
        ),
    ]
