# Generated by Django 4.2.1 on 2023-05-03 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cristal', '0006_alter_tarefa_mes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='status_entrega',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
