# Generated by Django 4.2.1 on 2023-05-04 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cristal', '0007_tarefa_status_entrega'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tarefa',
            new_name='TarefaModel',
        ),
    ]
