# Generated by Django 4.2.1 on 2023-05-09 14:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cristal', '0011_cliente_created_at_cliente_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
    ]
