# Generated by Django 4.2.1 on 2023-05-09 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cristal', '0012_emailmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailmodel',
            old_name='template',
            new_name='email_template',
        ),
        migrations.AddField(
            model_name='tarefamodel',
            name='email_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cristal.emailmodel'),
        ),
    ]
