# Generated by Django 4.2.1 on 2023-05-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cristal', '0013_rename_template_emailmodel_email_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailmodel',
            name='nome',
            field=models.CharField(default='modelo12', max_length=10),
            preserve_default=False,
        ),
    ]
